CATALOGUE_HOST: catalogue.dsops84.space
USER_HOST: user.dsops84.space
CART_HOST: cart.dsops84.space
MONGODB_HOST: mongodb.dsops84.space
SHIPPING_HOST: shipping.dsops84.space
PAYMENT_HOST: payment.dsops84.space
MYSQL_HOST: mysql.dsops84.space
REDIS_HOST: redis.dsops84.space
RABBITMQ_HOST: rabbitmq.dsops84.space